Liquid.Library.UI/Controllers/Api/BookController.cs
using Liquid.Library.Commands.Inventory.Books;
using Liquid.Library.Domain.Inventory;
using System;
using System.Threading.Tasks;
using System.Web.Http;

namespace Liquid.Library.UI.Controllers.Api
{
    public class BookController : ApiController
    {
        [HttpGet]
        [Route("api/books")]
        public async Task<IHttpActionResult> Get()
        {
            var command = new GetCommand();
            await command.Execute();

            return Ok(command.Books);
        }

        [HttpGet]
        [Route("api/books/{id}")]
        public async Task<IHttpActionResult> Get(Guid id)
        {
            if (id == null)
                return NotFound();
            
            var command = new LoadCommand() { Id = id };
            await command.Execute();

            return Ok(command.Book);
        }
        
        [HttpPost]
        [Route("api/books")]
        public async Task<IHttpActionResult> Post([FromBody]Book book)
        {
            if (book == null)
                return NotFound();

            if (!ModelState.IsValid)
                return BadRequest();

            var command = new PostCommand() { Book = book };
            await command.Execute();

            return Ok(command.Id);
        }

        [HttpPatch]
        [Route("api/books")]
        public async Task<IHttpActionResult> Patch([FromBody]Book book)
        {
            if (book == null)
                return NotFound();

            if (!ModelState.IsValid)
                return BadRequest();

            var command = new PatchCommand() { Book = book };
            await command.Execute();

            return Ok();
        }

        [HttpDelete]
        [Route("api/books/{id}")]
        public async Task<IHttpActionResult> Delete(Guid id)
        {
            if (id == null)
                return NotFound();

            var command = new DeleteCommand() { Id = id };
            await command.Execute();

            return Ok();
        }
    }
}

Liquid.Library.UI/Controllers/Api/MovieController.cs
using Liquid.Library.Commands.Inventory.Books;
using System;
using System.Threading.Tasks;
using System.Web.Http;

namespace Liquid.Library.UI.Controllers.Api
{
    public class MovieController : ApiController
    {
        [HttpGet]
        [Route("api/movies")]
        public async Task<IHttpActionResult> Get()
        {
            var command = new GetCommand();
            await command.Execute();

            return Ok(command.Books);
        }

        [HttpGet]
        [Route("api/movies/{id}")]
        public async Task<IHttpActionResult> Get(Guid id)
        {
            if (id == null)
                return NotFound();
            
            var command = new LoadCommand() { Id = id };
            await command.Execute();

            return Ok(command.Book);
        }

        [HttpPost]
        [Route("api/movies")]
        public async Task<IHttpActionResult> Post([FromBody]Domain.Inventory.Book book)
        {
            if (book == null)
                return NotFound();

            if (!ModelState.IsValid)
                return BadRequest();

            var command = new PostCommand() { Book = book };
            await command.Execute();

            return Ok(command.Id);
        }

        [HttpDelete]
        [Route("api/movies/{id}")]
        public async Task<IHttpActionResult> Delete(Guid id)
        {
            if (id == null)
                return NotFound();

            var command = new DeleteCommand() { Id = id };
            await command.Execute();

            return Ok();
        }
    }
}

Liquid.Library.UI/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Liquid.Library.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Liquid.Library.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Library of Verheijen";
}

<div class="page-content">
    <div class="page-info-wrapper">
        <div class="page-info">
            <div class="page-info-heading">Library of Verheijen</div>
            <table class="home-menu">
                <tr style="height:100px;">
                    <td valign="middle">
                        <a href="@Url.Action("Index", "Book")">
                            <div class="home-menu-item">
                                <p>Books</p>
                            </div>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td valign="middle">
                        <a href="@Url.Action("Index", "Movie")">
                            <div class="home-menu-item">
                                <p>Movie</p>
                            </div>
                        </a>
                    </td>
                </tr>

                    @*var topics = new[]
                    {
                            new { EntityName = "Book", DisplayName = "Books" },
                            new { EntityName = "Game", DisplayName = "Games" },
                            new { EntityName = "Movie", DisplayName = "Movies" },
                            new { EntityName = "Music", DisplayName = "Music" }
                        };

                    foreach (var topic in topics)
                    {
                        <tr style="height:100px;">
                            <td valign="middle">
                                <a href="@Url.Action("Index", @topic.EntityName)">
                                    <div class="home-menu-item">
                                        <p>@topic.DisplayName</p>
                                    </div>
                                </a>
                            </td>
                        </tr>
                    }*@
            </table>
        </div>
    </div>
</div>